package az.millikart.directory;

import az.millikart.directory.dto.CreateCompanyRequest;
import org.springframework.jdbc.core.JdbcTemplate;

// Фикстуры, общие для тестов directory.
final class DirectoryTestFixtures {

    private DirectoryTestFixtures() {
    }

    // Компания с кредами к провайдеру: без них API её не заводит (Р-93). Логин уникален, поэтому — по id;
    // пройдёт проверку, только если providerLogins завёл его в слепок (Р-94).
    static CreateCompanyRequest company(String id, String name) {
        return new CreateCompanyRequest(id, name, "MultiMerchantSys/" + id, "secret-" + id);
    }

    // Слепок логинов мультимерчантов (Р-94): таблицу держит ecom, в базе тестов directory её нет. Логин
    // каждой компании — активный, с одним активным мерчантом; колонки — те, что читает directory.
    static void providerLogins(JdbcTemplate jdbc, String... companyIds) {
        for (String companyId : companyIds) {
            providerLogin(jdbc, companyId, "Active", "Active", "M-" + companyId);
        }
    }

    static void providerLogin(JdbcTemplate jdbc, String login, String loginStatus, String linkStatus, String merchantRid) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS provider_logins (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "login varchar(128) NOT NULL, login_status varchar(32), link_status varchar(32), "
                + "merchant_rid varchar(64), merchant_title varchar(256), "
                + "synced_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL)");
        jdbc.update("DELETE FROM provider_logins WHERE login = ?", login);
        jdbc.update("INSERT INTO provider_logins (login, login_status, link_status, merchant_rid) VALUES (?, ?, ?, ?)",
                login, loginStatus, linkStatus, merchantRid);
    }

    // Строка справочника провайдера. Таблицу держит ecom, в базе тестов directory её нет, а завести
    // терминал теперь можно только выбором из справочника (Р-93). Колонки — те, что читает directory.
    static void providerTerminal(JdbcTemplate jdbc, String rid, String title, String login) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS provider_terminals (rid varchar(64) PRIMARY KEY, "
                + "title varchar(256), login varchar(128), active boolean NOT NULL DEFAULT true)");
        jdbc.update("DELETE FROM provider_terminals WHERE rid = ?", rid);
        jdbc.update("INSERT INTO provider_terminals (rid, title, login, active) VALUES (?, ?, ?, true)",
                rid, title, login);
    }
}
